[package]
name = "verification"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
rand_aes =  { path = "..", features = ["verification"] }

[[bin]]
name = "verification"
path = "src/bin/verification.rs"
